- name: install packages
  hosts: local
  connection: local
  tasks:
  - name: print packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - java